---

language: python
python: 2.7
sudo: yes

install:
  - pip install ansible==1.9.1

script:
  - ansible-galaxy install --force -r requirements.yml
  - ansible-playbook -i localhost, --connection=local playbook.yml
  - cd tests && bash test_idempotence.sh
